### Fancy Indexing

In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9] # 取得3-9下标的数

array([3, 4, 5, 6, 7, 8])

In [5]:
x[3:9:2] # 取得3-9下标的数，步长为2

array([3, 5, 7])

In [6]:
[x[3],x[5],x[8]] # 取得没有规律的数

[3, 5, 8]

In [7]:
ind = [3,5,8]
x[ind]

array([3, 5, 8])

In [8]:
ind = np.array([[0,2],
                [1,3]]) # 二维索引
x[ind] # 二维矩阵

array([[0, 2],
       [1, 3]])

In [9]:
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
row = np.array([0,1,2]) # 感兴趣的行索引
col = np.array([1,2,3]) # 感兴趣的列索引
X[row,col]

array([ 1,  6, 11])

In [13]:
X[0,col]  # 第0行的感兴趣列

array([1, 2, 3])

In [14]:
X[:2,col] # 0-2行的感兴趣列

array([[1, 2, 3],
       [5, 6, 7]])

In [15]:
col = [True,False,True,True]
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array的比较

In [16]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [18]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [19]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [20]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
np.sum(x <= 3) # True跟False当作1-0相加

4

In [25]:
np.count_nonzero(x <= 3) # 小于3 的非0元素的个数

4

In [26]:
np.any(x == 0) # 一旦存在0，就返回0

True

In [27]:
np.any(x < 0) # 没有小于零的数

False

In [28]:
np.all(x >= 0)

True

In [29]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
np.sum(x % 2 == 0) # 偶数的个数

8

In [31]:
np.sum(X % 2 == 0,axis = 1) # 沿着列的方向，即一行一行的

array([2, 2, 2, 2])

In [32]:
np.sum(X % 2 == 0,axis = 1) # 沿着行的方向，即一列一列的

array([2, 2, 2, 2])

In [33]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
np.sum((x > 3) & (x < 10)) # 一个&符号进行与的运算

6

In [35]:
np.sum((x > 3) && (x < 10)) # 错误的写法

SyntaxError: invalid syntax (<ipython-input-35-a73c46effeb2>, line 1)

In [37]:
np.sum((x % 2 == 0) | (x > 10))

11

In [38]:
np.sum(~(x == 0)) # ~非运算

15

In [39]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [40]:
x[x% 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [43]:
X[X[:,3] % 3 == 0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

Pandas 