## Numpy.array 中的运算

给定一个向量，让向量中的每一个数乘以2

a = (0,1,2)

a*2 = (0,2,4)

In [2]:
n = 10 # 10维向量
L = [i for i in range(n)]

In [3]:
2 * L # 首位相连，长度乘以2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
A = []  # 循环遍历
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:
n = 100000
L = [i for i in range(n)]

In [6]:
%%time
A = []  # 循环遍历,耗时太长
for e in L:
    A.append(2*e)

Wall time: 27 ms


In [7]:
%%time
A = [2*e for e in L]  # 表达式格式快于循环遍历

Wall time: 14.2 ms


In [8]:
import numpy as np
L = np.arange(n)

In [9]:
%%time 
A = np.array(2*e for e in L)  # 快于list完成2倍相乘

Wall time: 4.19 ms


In [10]:
%%time
A = 2 * L   # 简便完成

Wall time: 0 ns


In [11]:
A

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [12]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Universal Funcation

In [13]:
X = np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [15]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X / 2  # 浮点数的除法

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [17]:
X // 2  # 整数的除法

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [18]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [19]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [20]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [21]:
np.abs(X) # 取绝对值

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
np.sin(X) # 三角函数

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [23]:
np.cos(X) 

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [24]:
np.exp(X) # 对所有函数取e的x次方

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [26]:
np.power(3,X) # 幂运算

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [27]:
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [28]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [29]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [30]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵运算

In [31]:
A = np.arange(4).reshape(2,2)

In [32]:
A

array([[0, 1],
       [2, 3]])

In [33]:
B = np.full((2,2),10)

In [34]:
B

array([[10, 10],
       [10, 10]])

In [35]:
A + B

array([[10, 11],
       [12, 13]])

In [36]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [37]:
A * B #对应元素相乘，非矩阵乘法

array([[ 0, 10],
       [20, 30]])

In [38]:
A / B # 对应元素相初

array([[0. , 0.1],
       [0.2, 0.3]])

In [39]:
A.dot(B) # 矩阵的乘法

array([[10, 10],
       [50, 50]])

In [40]:
A

array([[0, 1],
       [2, 3]])

In [41]:
A.T # 矩阵的转置

array([[0, 2],
       [1, 3]])

In [42]:
C = np.full((3,3),666)

In [43]:
C

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [44]:
A.dot(C) # 无法进行矩阵的乘法

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

### 向量和矩阵的运算

In [45]:
v = np.array([1,2])

In [46]:
A

array([[0, 1],
       [2, 3]])

In [47]:
v + A # numpy自动跟每一行的向量相应相加

array([[1, 3],
       [3, 5]])

In [49]:
np.vstack([v] * A.shape[0]) # 将v堆叠成A的0shape

array([[1, 2],
       [1, 2]])

In [ ]:
np.tile(v,(2,1)) # 在行方向上堆叠2次，列方向上堆叠1次

In [51]:
np.tile(v,(2,1)) + A 

array([[1, 3],
       [3, 5]])

In [52]:
v

array([1, 2])

In [53]:
A

array([[0, 1],
       [2, 3]])

In [54]:
v * A # 每一个向量相乘

array([[0, 2],
       [2, 6]])

In [55]:
v.dot(A) # 矩阵之间的乘法

array([4, 7])

In [56]:
A.dot(v) # 矩阵乘向量，numpy自动判断取行向量还是列向量 

array([2, 8])

### 矩阵的逆

In [57]:
A

array([[0, 1],
       [2, 3]])

In [58]:
np.linalg.inv(A) # 矩阵的逆

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [59]:
invA = np.linalg.inv(A) # 保存一下

In [60]:
A.dot(invA) # 原矩阵乘逆矩阵得到单位矩阵

array([[1., 0.],
       [0., 1.]])

In [61]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [62]:
X = np.arange(16).reshape(2,8)

In [63]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [64]:
np.linalg.inv(X) # 无法求逆

LinAlgError: Last 2 dimensions of the array must be square

In [65]:
pinvX = np.linalg.pinv(X) # 求伪逆矩阵

In [66]:
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [67]:
X.dot(pinvX) # 相乘得单位矩阵

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])