# numpy.array 基础

In [2]:
import numpy

In [3]:
numpy.__version__

'1.14.0'

In [4]:
import numpy as np

In [5]:
np.__version__

'1.14.0'

## Python List的特点

In [7]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
L[5]

5

In [9]:
L[5] = "Machne Learning"

In [10]:
L

[0, 1, 2, 3, 4, 'Machne Learning', 6, 7, 8, 9]

In [11]:
import array

In [12]:
arr = array.array('i',[i for i in range(10)])

In [13]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[5]

5

In [15]:
arr[5] = 100

In [16]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [17]:
arr[5] = "machine learning"

TypeError: an integer is required (got type str)

## numpy.array

In [18]:
nparr = np.array([i for i in range(10)]) 

In [20]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr[5]

5

In [22]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [23]:
nparr[5] = 'Machine Learning'

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [24]:
nparr.dtype

dtype('int32')

In [25]:
nparr[5] = 5.0

In [26]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
nparr.dtype

dtype('int32')

In [28]:
nparr[3] = 3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
nparr.dtype

dtype('int32')

In [32]:
nparr2 = np.array([1,2,3.14])
nparr2.dtype

dtype('float64')

## 其他创建 numpy.array的方法

In [34]:
np.zeros(10)  # 全为0的大小10的数组

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.zeros(10).dtype  # 默认浮点型

dtype('float64')

In [36]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
np.zeros((3,5)) # 传入二维的元组，生成矩阵

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.zeros(shape=(3,5),dtype=int) # 参数

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [39]:
np.ones(10)  # 生成全1的向量

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
np.ones((3,5))  # 全1矩阵

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.full(shape=(3,5),fill_value=666.0)  # full()方法生成指定数据矩阵，.0默认浮点型

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

### arange方法

In [45]:
[i for i in range(0,20,2)] 

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [47]:
np.arange(0,20,2)  # 与range()参数意义相同

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
np.arange(0,1,0.2)  # arange()可以接受步长为0.2的数组

array([0. , 0.2, 0.4, 0.6, 0.8])

In [49]:
np.arange(0,10)  # 默认步长为1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(10)   # 默认从0开始

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace 方法

In [51]:
np.linspace(0,20,10) # 参数与arange()相同，10表示等长的截出10个元素，包括0跟20

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [52]:
np.linspace(0,20,11) # 一共需要截出11个数

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random 方法  生成随机数

In [56]:
np.random.randint(0,10)  # 0-10之间的随机数

1

In [57]:
np.random.randint(0,10,10) #生0-10的大小为10的随机数组，不包含10本身，无法取到10

array([5, 0, 5, 2, 6, 0, 6, 7, 0, 0])

In [58]:
np.random.randint(0,1,10) # 不包含1本身

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
np.random.randint(4,8,size=(3,5)) # 生成二维随机矩阵

array([[6, 5, 4, 5, 5],
       [4, 5, 4, 7, 6],
       [4, 4, 6, 7, 6]])

In [60]:
np.random.randint(4,8,size=(3,5))  #与上述不同

array([[7, 7, 7, 6, 4],
       [4, 4, 5, 7, 5],
       [4, 6, 7, 5, 7]])

In [66]:
np.random.seed(666)  # 设定种子  固定随机数

In [67]:
np.random.randint(4,8,size=(3,5)) 

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [68]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))   #随机种子指定随机数

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [69]:
np.random.random()  # 默认生成01之间的浮点数

0.2811684913927954

In [70]:
np.random.random(10) # 指定10个数据，随机向量  默认均匀分布

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [71]:
np.random.random((3,5)) # 生成0-1之间的[3,5]随机浮点矩阵   默认均匀分布

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

### normal  方法  正态分布随机数

In [72]:
np.random.normal()  #均值为0，方差为1 的随机浮点数

0.7760516793129695

In [75]:
np.random.normal(10,100) # 均值为10，方差为100 的随机浮点数

117.8561378074435

In [76]:
np.random.normal(0,1,(3,5)) # 均值为0，方差为1 的随机浮点[3,5]矩阵数据

array([[-0.79783572,  1.1701326 ,  0.1121217 ,  0.03185388, -0.19206285],
       [ 0.78611284, -1.69046314, -0.98873907,  0.31398563,  0.39638567],
       [ 0.57656584, -0.07019407,  0.91250436,  1.00470497,  0.41859929]])

### 查询文档

In [77]:
np.random.normal?  # ？查看文档

In [78]:
np.random?

In [79]:
help(np.random.normal)  # help()方法 

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap