In [1]:
from mxnet import nd

In [2]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [3]:
x.shape

(12,)

In [4]:
x.size

12

In [5]:
X = x.reshape((3, 4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [6]:
 nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [7]:
nd.ones((3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [8]:
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [9]:
# 均值为０,标准差为１
nd.random_normal(0, 1, shape=(3, 4))


[[ 2.2122064   0.7740038   1.0434403   1.1839255 ]
 [ 1.8917114  -1.2347414  -1.771029   -0.45138445]
 [ 0.57938355 -1.856082   -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>

In [10]:
Ｘ + Y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [11]:
X * Y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [12]:
X / Y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [13]:
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [14]:
Y.exp()


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [15]:
nd.dot(X, Y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [16]:
nd.concat(X, Y, dim=0), nd.concat(X, Y, dim=1)

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  1.  4.  3.]
  [ 1.  2.  3.  4.]
  [ 4.  3.  2.  1.]]
 <NDArray 6x4 @cpu(0)>,
 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
  [ 4.  5.  6.  7.  1.  2.  3.  4.]
  [ 8.  9. 10. 11.  4.  3.  2.  1.]]
 <NDArray 3x8 @cpu(0)>)

In [17]:
X == Y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [18]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [19]:
X.norm().asscalar()

22.494442

In [20]:
A = nd.arange(3).reshape(3, 1)
B = nd.arange(2).reshape(1, 2)
A, B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [21]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [22]:
X[1:3], X

(
 [[ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 2x4 @cpu(0)>,
 
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 3x4 @cpu(0)>)

In [23]:
X[1, 2] = 9
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [24]:
X[1:2,:] = 9
X


[[ 0.  1.  2.  3.]
 [ 9.  9.  9.  9.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [25]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [27]:
Z = Y.zeros_like()
before = id(Z)
Z[:] = X + Y
id(Z) == before

True

In [28]:
import numpy as np

In [29]:
P = np.ones((2, 3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [30]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [35]:
X = X + 4
X


[[ 4.  5.  6.  7.]
 [13. 13. 13. 13.]
 [12. 13. 14. 15.]]
<NDArray 3x4 @cpu(0)>

In [37]:
Y, X > Y

(
 [[ 2.  2.  6.  6.]
  [10. 11. 12. 13.]
  [12. 12. 12. 12.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[1. 1. 0. 1.]
  [1. 1. 1. 0.]
  [0. 1. 1. 1.]]
 <NDArray 3x4 @cpu(0)>)

### 自动求梯度

In [38]:
from mxnet import autograd

In [39]:
x = nd.arange(4).reshape(4, 1)
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [46]:
x.attach_grad() # 申请存储梯度所需要的梯度

In [47]:
with autograd.record():
    y = 2 * nd.dot(x.T, x)
y


[[28.]]
<NDArray 1x1 @cpu(0)>

In [48]:
y.backward()

In [51]:
assert (x.grad - 4 * x).norm().asscalar() == 0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [52]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True


In [53]:
def f(a):
    b  = a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [54]:
a = nd.random.normal(shape=1)
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()

In [55]:
a.grad == c / a


[1.]
<NDArray 1 @cpu(0)>

In [60]:
print(dir(nd.random))

['NDArray', '_Null', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_internal', '_random_helper', 'current_context', 'exponential', 'exponential_like', 'gamma', 'gamma_like', 'generalized_negative_binomial', 'generalized_negative_binomial_like', 'multinomial', 'negative_binomial', 'negative_binomial_like', 'normal', 'normal_like', 'numeric_types', 'poisson', 'poisson_like', 'randint', 'randn', 'shuffle', 'uniform', 'uniform_like']


In [61]:
help(nd.ones_like)

Help on function ones_like:

ones_like(data=None, out=None, name=None, **kwargs)
    Return an array of ones with the same shape and type
    as the input array.
    
    Examples::
    
      x = [[ 0.,  0.,  0.],
           [ 0.,  0.,  0.]]
    
      ones_like(x) = [[ 1.,  1.,  1.],
                      [ 1.,  1.,  1.]]
    
    
    
    Parameters
    ----------
    data : NDArray
        The input
    
    out : NDArray, optional
        The output NDArray to hold the result.
    
    Returns
    -------
    out : NDArray or list of NDArrays
        The output of this function.

