### 测试我们的算法

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [3]:
iris = datasets.load_iris() # 加载鸢尾花的数据集

In [4]:
X = iris.data # 鸢尾花的数特征矩阵
y = iris.target # 结果标签对应的向量

In [5]:
X.shape # 查看X数据的形状

(150, 4)

In [6]:
y.shape

(150,)

### train_text_split

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
suffle_indexes = np.random.permutation(len(X)) # X长度的数据随机打乱,随机的索引值

In [10]:
suffle_indexes

array([ 41, 112, 128,  29,  52,   9, 107, 137,  31,  39,  28,  80,  12,
       118,  50,  71,  37,  98,  14, 146,  45,  49,   2,  57,  89,  95,
        65, 127,  48, 143,  97,  26, 132,  22,  20, 125,  35, 106, 144,
        91, 115,  19, 117,  79, 108,  75, 138, 126,  68,  34, 122,  99,
        33,  86, 130, 104, 113, 136, 100,   8,  21, 141,  77,  40,  62,
        13, 121,  46,  23,  36,  73,   4, 111, 145,  69, 134,   7, 142,
        85, 133,  15,  43,  66, 116,  94, 124,  27, 101, 103,  76,  81,
        30, 105,  25,  67, 147, 131,   1, 140,  24, 114,  44, 110,  17,
         6,  92,  72,  11,   5, 123,  96,  87,  61,  74,  60,  56, 135,
        59,  38,   3, 148, 149,  51,  83,  10, 120,  18,  88,   0,  55,
        16,  32,  93,  53, 139,  58,  54,  90,  64,  78, 102, 109, 119,
        84,  82,  47,  63,  70, 129,  42])

In [11]:
test_ratio = 0.2

In [14]:
test_size = int(len(X) * test_ratio) 

In [15]:
test_size

30

In [17]:
test_indexes = suffle_indexes[:test_size]
train_indexes = suffle_indexes[test_size:]

In [18]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [20]:
print(X_test)
print(y_test)

[[4.5 2.3 1.3 0.3]
 [6.8 3.  5.5 2.1]
 [6.4 2.8 5.6 2.1]
 [4.7 3.2 1.6 0.2]
 [6.9 3.1 4.9 1.5]
 [4.9 3.1 1.5 0.1]
 [7.3 2.9 6.3 1.8]
 [6.4 3.1 5.5 1.8]
 [5.4 3.4 1.5 0.4]
 [5.1 3.4 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [5.5 2.4 3.8 1.1]
 [4.8 3.  1.4 0.1]
 [7.7 2.6 6.9 2.3]
 [7.  3.2 4.7 1.4]
 [6.1 2.8 4.  1.3]
 [4.9 3.1 1.5 0.1]
 [5.1 2.5 3.  1.1]
 [5.8 4.  1.2 0.2]
 [6.3 2.5 5.  1.9]
 [4.8 3.  1.4 0.3]
 [5.  3.3 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.9 2.4 3.3 1. ]
 [5.5 2.5 4.  1.3]
 [5.7 3.  4.2 1.2]
 [6.7 3.1 4.4 1.4]
 [6.1 3.  4.9 1.8]
 [5.3 3.7 1.5 0.2]
 [6.8 3.2 5.9 2.3]]
[0 2 2 0 1 0 2 2 0 0 0 1 0 2 1 1 0 1 0 2 0 0 0 1 1 1 1 2 0 2]


### 使用我们的算法

In [33]:
from kNN import train_test_split # 导入我们的方法
from kNN import KNNClassifier

In [41]:
X_train,y_train,X_test,y_test = train_test_split(X,y) # 获取我们的训练跟测试数据集

In [42]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [43]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [44]:
my_knn_clf = KNNClassifier(k=3)

In [45]:
my_knn_clf.fit(X_train,y_train)

In [46]:
my_knn_clf.predit(X_test)

array([1, 2, 2, 1, 0, 0, 0, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2, 0, 1, 2, 2, 2,
       2, 2, 1, 0, 0, 0, 1, 0])

In [47]:
y_predict = my_knn_clf.predit(X_test)

In [48]:
y_predict

array([1, 2, 2, 1, 0, 0, 0, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2, 0, 1, 2, 2, 2,
       2, 2, 1, 0, 0, 0, 1, 0])

In [49]:
y_test

array([1, 2, 2, 1, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1, 2, 2, 2,
       2, 2, 1, 0, 0, 0, 1, 0])

In [50]:
sum(y_predict == y_test)

29

In [51]:
sum(y_predict == y_test)/len(y_test)

0.9666666666666667

### sklearn中的train_test_split

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=666)

In [54]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [55]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
