## 合并操作

In [3]:
import numpy as np

In [4]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [5]:
x

array([1, 2, 3])

In [6]:
y

array([3, 2, 1])

In [7]:
np.concatenate([x,y]) # 拼接函数,参数为想要合并的向量

array([1, 2, 3, 3, 2, 1])

In [8]:
z = np.array([666,666,666])

In [9]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [11]:
A = np.array([[1,2,3],
             [4,5,6]])

In [12]:
np.concatenate([A,A]) # 二维矩阵拼接

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [13]:
np.concatenate([A,A],axis=0) #沿着行的方向拼接， axis表示轴的方向 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [14]:
np.concatenate([A,A],axis=1) #沿着列的方向拼接， axis表示轴的方向 

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [16]:
np.concatenate([A,z.reshape(1,-1)]) # 将z一维向量拼接到二维矩阵A当中

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [17]:
A # A并未改变

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
A2 = np.concatenate([A,z.reshape(1,-1)])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [19]:
np.vstack([A,z]) # vstack函数 ，竖直方向数据的堆叠

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [20]:
B = np.full((2,2),100)  # 先创建2行2列的100矩阵
B

array([[100, 100],
       [100, 100]])

In [21]:
np.hstack([A,B]) # hstack函数 ，水平方向数据的堆叠

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割

In [22]:
x = np.arange(10)

In [23]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x1,x2,x3 = np.split(x,[3,7]) # 指定两个分割点 3 和 7

In [25]:
x1

array([0, 1, 2])

In [26]:
x2

array([3, 4, 5, 6])

In [27]:
x3

array([7, 8, 9])

In [29]:
x1,x2 = np.split(x,[5]) # 5为分隔点

In [30]:
x1

array([0, 1, 2, 3, 4])

In [31]:
x2

array([5, 6, 7, 8, 9])

In [32]:
A = np.arange(16).reshape(4,4) # 创建0-16的向量并转为[4,4]矩阵
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
A1,A2 = np.split(A,[2])

In [34]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
A1,A2 = np.split(A,[2],axis = 1)  # 水平分割
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [37]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [38]:
upper,lower = np.vsplit(A,[2]) # 上下两个子矩阵
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [39]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
left,right = np.hsplit(A,[2])  # 左右两个子矩阵
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [41]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [42]:
data = np.arange(16).reshape([4,4])
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
x,y = np.hsplit(data,[-1]) # 从倒数第一列分割
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [44]:
y # 所切割的最后一列

array([[ 3],
       [ 7],
       [11],
       [15]])

In [45]:
y[:,0]  # 所有行的第一列，转为向量

array([ 3,  7, 11, 15])