## Numpy.array 中的运算

给定一个向量，让向量中的每一个数乘以2

a = (0,1,2)

a*2 = (0,2,4)

In [1]:
n = 10 # 10维向量
L = [i for i in range(n)]

In [2]:
2 * L # 首位相连，长度乘以2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []  # 循环遍历
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:
n = 100000
L = [i for i in range(n)]

In [7]:
%%time
A = []  # 循环遍历,耗时太长
for e in L:
    A.append(2*e)

Wall time: 32.9 ms


In [12]:
%%time
A = [2*e for e in L]  # 表达式格式快于循环遍历

Wall time: 11 ms


In [17]:
import numpy as np
L = np.arange(n)

In [18]:
%%time 
A = np.array(2*e for e in L)  # 快于list完成2倍相乘

Wall time: 6.98 ms


In [19]:
%%time
A = 2 * L   # 简便完成

Wall time: 4.98 ms


In [20]:
A

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [21]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Universal Funcation

In [22]:
X = np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [24]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
X / 2  # 浮点数的除法

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [31]:
X // 2  # 整数的除法

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)