In [1]:
import numpy as np

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
X = np.arange(15).reshape(3,5) # reshape()方法，
X  #[3，5] 0-14的二维数组

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [8]:
x.ndim  # 数组的维度

1

In [9]:
X.ndim

2

In [10]:
x.shape # 返回一个元组，一个维度，每个维度10个元素

(10,)

In [11]:
X.shape # 三个维度，每个维度5个元素

(3, 5)

In [12]:
x.size # 返回元素个数

10

In [13]:
X.size

15

### numpy.array 的数据访问

In [14]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[0]

0

In [16]:
x[-1] # 倒数第一的元素

9

In [17]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
X[0][0] # 访问第一个元素 但是不建议这么写

0

In [19]:
X[(0,0)] # 元组访问

0

In [20]:
X[(2,2)] # 访问

12

In [21]:
x[0:5] # 切片

array([0, 1, 2, 3, 4])

In [22]:
x[:5] # 默认从头开始

array([0, 1, 2, 3, 4])

In [23]:
x[5:] # 默认到结尾

array([5, 6, 7, 8, 9])

In [24]:
x[::2] # 步长为2的整体访问

array([0, 2, 4, 6, 8])

In [25]:
x[::-1] # 倒着访问

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
X[:2,:3] # 前两行，前三列

array([[0, 1, 2],
       [5, 6, 7]])

In [28]:
X[:2][:3] # 无法取得前两行前三列

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
X[:2] # 前两行

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
X[:2][:3] # 默认还是列方向取数

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
X[:2,::2] # 前两行，每一行，从头到尾间隔为2

array([[0, 2, 4],
       [5, 7, 9]])

In [33]:
X[::-1,::-1] # 整体倒着数，相当于转置

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [34]:
X[0,:] # 行数取0 列数从头到尾

array([0, 1, 2, 3, 4])

In [35]:
X[0,:].ndim

1

In [36]:
X[:,0] # 取第一列

array([ 0,  5, 10])

In [37]:
X[:,0].ndim

1

In [39]:
subX = X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [40]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [41]:
X # 对于X来说 也受到了改变，子矩阵的修改会改变原矩阵的值

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [42]:
X[0,0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
subX # 原矩阵改变，子矩阵也会跟着改变

array([[0, 1, 2],
       [5, 6, 7]])

In [45]:
subX = X[:2,:3].copy() # 使用copy()函数脱离关系
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [46]:
subX[0,0] = 100 # 只有subX改变了
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [47]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape 改变维度

In [49]:
x.shape

(10,)

In [60]:
x.ndim

1

In [62]:
x.reshape(2,5)  # 改为2×5的矩阵

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
x # 不会改变x的数值

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
B = x.reshape(1,10) # B为二维数组
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
B.ndim  # B为二维数组

2

In [71]:
B.shape # 1行，每行有10列

(1, 10)

In [72]:
x.shape

(10,)

In [73]:
x.reshape(10,-1) # 不管每行有几个元素 但是是10列

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [75]:
x.reshape(-1,10) 

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])